---
version: 2
log-file: /home/syu-fu/Documents/Projects/output.log
log-level: 1
root-markers:
  - node_modules/
  - .git/
lint-debounce: 0.5s
tools:
  javascript-eslint: &javascript-eslint
    lint-command: 'eslint -f visualstudio --stdin --stdin-filename ${INPUT}'
    lint-ignore-exit-code: true
    lint-stdin: true
    lint-formats:
      - "%f(%l,%c): %tarning %m"
      - "%f(%l,%c): %rror %m"

  prettier: &prettier
    format-command: 'npx --no-install prettier --stdin-filepath ${INPUT}'
    format-stdin: true

  textlint-lint: &textlint-lint
    lint-command: 'textlint --format unix --stdin --stdin-filename ${INPUT}'
    lint-ignore-exit-code: true
    lint-stdin: true
    lint-formats:
    - "%f:%l:%c: %m [%trror/%r]"

  vim-vint: &vim-vint
    lint-command: 'vint -'
    lint-stdin: true
    lint-formats:
      - '%f:%l:%c: %m'

  json-jq: &json-jq
    lint-command: 'jq .'

languages:
  typescript:
    - <<: *javascript-eslint
    - <<: *prettier

  markdown:
    - <<: *textlint-lint

  json:
    - <<: *json-jq

  vim:
    - <<: *vim-vint

