#!/bin/bash

set -eu

if [ "$*" = "x-usage" ]; then
	echo "open today's daily memo"
	exit
fi

filename="$(date +%Y-%m-%d).md"

if memo cat "$filename" &> /dev/null; then
	memo edit "$filename"
else
	# memoコマンドで空のタイトルの指定方法がないためnew -> editの流れで対応
	echo -e "\n" | memo new
	memo edit "$filename"
fi
