# plugin_manager {{{
[[plugins]]
repo = 'Shougo/dein.vim'
# }}}

# view {{{
[[plugins]]
repo = 'morhetz/gruvbox'

[[plugins]]
repo = 'sainnhe/gruvbox-material'

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = 'source $XDG_CONFIG_HOME/nvim/plugins/settings/lightline.vim'

[[plugins]]
repo = 'shinchu/lightline-gruvbox.vim'

[[plugins]]
repo = 'ryanoasis/vim-devicons'
# }}}

# setting deno {{{
[[plugins]]
repo = 'vim-denops/denops.vim'
# }}}

