# plugin_manager {{{
[[plugins]]
repo = 'Shougo/dein.vim'
# }}}

# view {{{
[[plugins]]
repo = 'sainnhe/gruvbox-material'

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = 'source $XDG_CONFIG_HOME/nvim/plugins/settings/lightline.rc.vim'

[[plugins]]
repo = 'mengelbrecht/lightline-bufferline'

[[plugins]]
repo = 'Syu-fu/nvim-lightline-lsp'

[[plugins]]
repo = 'ryanoasis/vim-devicons'
# }}}

# git {{{
[[plugins]]
repo = 'lambdalisue/gina.vim'

[[plugins]]
repo = 'airblade/vim-gitgutter'
hook_add = '''
    set updatetime=100
    let g:gitgutter_map_keys = 0
'''
# }}}

# setting deno {{{
[[plugins]]
repo = 'vim-denops/denops.vim'
# }}}

