hook_add = '''
'''

[ftplugin]

gitcommit = '''
function! s:select_type() abort
  let line = substitute(getline('.'), '^#\s*', '', 'g')
  let title = printf('%s: ', split(line, ' ')[0])

  silent! normal! "_dip
  silent! put! =title
  silent! startinsert!
endfunction

nnoremap <buffer> <CR><CR> <Cmd>call <SID>select_type()<CR>
'''

go = '''
nnoremap <buffer><silent> <Leader>t :<C-u>QuickRun -mode n go/test<CR>
setlocal noexpandtab
'''

typescript = '''
setlocal shiftwidth=2
'''

typescriptreact = '''
setlocal shiftwidth=2 softtabstop=2 tabstop=2
'''
