# filer{{{

# ファイラープラグイン
[[plugins]]
repo = 'lambdalisue/fern.vim'
hook_add = 'nnoremap <silent> <Leader>t :Fern . -reveal=% -drawer -toggle -width=40<CR>'
hook_source = 'source $XDG_CONFIG_HOME/nvim/plugins/settings/fern.rc.vim'
on_cmd = ['Fern']

# ファイルのアイコン付け
[[plugins]]
repo = 'lambdalisue/fern-renderer-nerdfont.vim'
on_source = 'fern.vim'

# ファイルのアイコンに色付け
[[plugins]]
repo = 'lambdalisue/glyph-palette.vim'
on_source = 'fern.vim'

# ファイルアイコンの依存プラグイン
[[plugins]]
repo = 'lambdalisue/nerdfont.vim'
on_source = 'fern.vim'

# ファイルのプレビュー
[[plugins]]
repo = 'yuki-yano/fern-preview.vim'
on_source = 'fern.vim'

# git statusを表示
[[plugins]]
repo = 'lambdalisue/fern-git-status.vim'
on_source = 'fern.vim'

# }}}

# man {{{

# helpの表示を日本語に
[[plugins]]
repo = 'vim-jp/vimdoc-ja'
hook_add = 'set helplang=ja,en'

# fzf{{{
[[plugins]]
repo = 'junegunn/fzf'

[[plugins]]
repo = 'yuki-yano/fzf-preview.vim'
on_source = 'fzf'
rev = 'release/rpc'
hook_add = 'source $XDG_CONFIG_HOME/nvim/plugins/settings/fzf.rc.vim'

# }}}

[[plugins]]
repo = 'cohama/lexima.vim'

# syntax-highlight {{{
[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter'
if = 'has("nvim")'
on_event = 'BufRead'
hook_source = '''
  luafile $XDG_CONFIG_HOME/nvim/lua/treesitter_rc.lua
'''
# }}}

[[plugins]]
repo = 'hrsh7th/vim-vsnip'
on_event = ['InsertEnter', 'CmdlineEnter']
depends = ['vim-vsnip-integ', 'friendly-snippets']
hook_add = '''
  imap <expr> <C-j> vsnip#expandable() ? '<Plug>(vsnip-expand)' : '<C-j>'
  smap <expr> <C-j> vsnip#expandable() ? '<Plug>(vsnip-expand)' : '<C-j>'
  imap <expr> <C-f> vsnip#jumpable(1)  ? '<Plug>(vsnip-jump-next)' : '<C-f>'
  smap <expr> <C-f> vsnip#jumpable(1)  ? '<Plug>(vsnip-jump-next)' : '<C-f>'
  imap <expr> <C-b> vsnip#jumpable(-1) ? '<Plug>(vsnip-jump-prev)' : '<C-b>'
  smap <expr> <C-b> vsnip#jumpable(-1) ? '<Plug>(vsnip-jump-prev)' : '<C-b>'
  let g:vsnip_filetypes = {}
'''

[[plugins]]
repo = 'hrsh7th/vim-vsnip-integ'

[[plugins]]
repo = 'rafamadriz/friendly-snippets'

[[plugins]]
repo = 'neovim/nvim-lspconfig'
if = 'has("nvim")'
on_event = 'BufRead'
hook_source = '''
  luafile $XDG_CONFIG_HOME/nvim/lua/lsp_rc.lua
'''

[[plugins]]
repo = 'williamboman/nvim-lsp-installer'
on_source = 'nvim-lspconfig'

[[plugins]]
repo = 'matsui54/denops-signature_help'
on_source = 'ddc.vim'
hook_source = 'call signature_help#enable()'

[[plugins]]
repo = 'matsui54/denops-popup-preview.vim'
on_source = 'ddc.vim'
hook_source = 'call popup_preview#enable()'

# git {{{
[[plugins]]
repo = 'lambdalisue/gina.vim'
on_cmd = 'Gina'

[[plugins]]
repo = 'airblade/vim-gitgutter'
on_event = 'BufRead'
hook_add = '''
    set updatetime=100
    let g:gitgutter_map_keys = 0
'''
# }}}


