function Select_type()
  local line = vim.fn.substitute(vim.fn.getline('.'), '^;\\s*', '', 'g')
  local title = string.format('%s: ', vim.fn.split(line, ' ')[1])
  vim.api.nvim_feedkeys(vim.api.nvim_replace_termcodes('"_dip', true, true, true), 'n', true)
  vim.schedule(function()
    vim.api.nvim_put({ title }, 'c', true, true)
    vim.cmd('silent! startinsert!')
  end)
end
vim.api.nvim_buf_set_keymap(0, 'n', '<CR><CR>', '<Cmd>lua Select_type()<CR>', { noremap = true, silent = true })
