shell = "zsh"

[templates]
defer = "{{ hooks?.pre | nl }}{% for file in files %}zsh-defer source \"{{ file }}\"\n{% endfor %}{{ hooks?.post | nl }}"
PATH = 'export PATH="$PATH:{{ dir }}"'

[plugins.zsh-defer]
github = "romkatv/zsh-defer"
hooks.post = '''
zsh-defer source $ZDOTDIR/rc/function.zsh
zsh-defer source $ZDOTDIR/rc/completion.zsh
'''

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"
apply = ["defer"]
hooks.post = '''
source $ZDOTDIR/plugrc/autosuggestion.zsh
'''

[plugins.zsh-syntax-highlighting]
github = "zdharma-continuum/fast-syntax-highlighting"
apply = ["defer"]

[plugins.zsh-completions]
github = "zsh-users/zsh-completions"
apply = ["defer"]

[plugins.zabrze]
inline = '''
eval "$(zabrze init --bind-keys)"
'''

[plugins.powerlevel10k]
github = "romkatv/powerlevel10k"
hooks.post = '''
source $ZDOTDIR/plugrc/p10k.zsh
'''

[plugins.mise]
inline = '''
eval "$(mise activate zsh)"
'''

[plugins.fzf-tab]
github = "Aloxaf/fzf-tab"
apply = ["defer"]
