name: benchmark
on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  # deployments permission to deploy GitHub pages website
  deployments: write
  # contents permission to update benchmark contents in gh-pages branch
  contents: write

jobs:
  benchmark:
    runs-on: ubuntu-latest
    container: archlinux:latest
    steps:
      - uses: actions/checkout@v1
      - name: Update packages
        run: pacman -Syyu --noconfirm
      - name: Install required packages
        run: pacman -S --noconfirm git sudo neovim zsh curl
      - name: fatal unsafe repository (REPO is owned by someone else)
        run: git config --global --add safe.directory /__w/dotfiles/dotfiles
      - name: Install dotfiles
        run: sudo bash -c './install.sh'
      - name: Add user
        run: useradd builduser -m
      - name: Add sudor
        run: echo 'builduser ALL=(ALL) ALL' >> /etc/sudoers
      - name: Change password
        run: passwd -d builduser
      - name: Install zsh plugins
        run: zsh
        shell: zsh -li --rcs {0}
        env:
          TERM: screen-256color
      - name: Install neovim plugins
        run: nvim -c q
      - name: Install packages required benchmark
        run: pacman -S --noconfirm time

      - name: Run benchmark
        run: ./bin/benchmark.sh | tee /tmp/result-benchmark.json
        shell: zsh -li --rcs {0}
        env:
          TERM: screen-256color

      - name: Upload benchmark
        uses: benchmark-action/github-action-benchmark@v1
        with:
          tool: customSmallerIsBetter
          output-file-path: /tmp/result-benchmark.json
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: true
          comment-on-alert: true
          fail-on-alert: true
          alert-threshold: "3000%"
          alert-comment-cc-users: "@Syu-fu"
